### ISSUE TITLE
非常感谢

### ISSUE THREAD

**Issue by LeoBoy1st** [futuretech6/clash.meta-docker#1]
找了好久，找到您的这个镜像，直接部署成功并使用到现在。
使用过程中有几个疑问，您方便的话解惑一下。
是否支持自动更新订阅？因为买的订阅不是特别稳定，隔三差五就需要手动更新下配置文件并重启。
能否设置个订阅链接，直接下载并更新应用呢？
另外，可否设置账号密码，我想部署在公网上，手机软件设置代理直连，有账号密码的话，会安全一点。

**Comment by futuretech6** [comment]
> 是否支持自动更新订阅？因为买的订阅不是特别稳定，隔三差五就需要手动更新下配置文件并重启。

推荐自己写一份本地配置，并且使用 [proxy-providers](https://wiki.metacubex.one/config/proxy-providers/) 来维持你的订阅代理列表，并使用其中的 [interval](https://wiki.metacubex.one/config/proxy-providers/#interval) 字段实现自动更新；或者你可以自己写一个 crontab 任务来定时下载你的订阅配置

> 能否设置个订阅链接，直接下载并更新应用呢？

同上

> 另外，可否设置账号密码，我想部署在公网上，手机软件设置代理直连，有账号密码的话，会安全一点。

代理密码 https://wiki.metacubex.one/config/general/#_3

API controller 密码 https://wiki.metacubex.one/config/general/#api

**Comment by LeoBoy1st** [comment]
非常感谢，已解决。
