### ISSUE TITLE
再次叨扰

### ISSUE THREAD

**Issue by LeoBoy1st** [futuretech6/clash.meta-docker#2]
我现在在armbian系统（镜像名：Armbian_24.11.0_amlogic_s905l3a_jammy_6.6.58_server_2024.11.01.img，系统信息如下：Linux armbian 6.6.58-ophub #1 SMP Thu Oct 24 11:41:04 EDT 2024 aarch64 aarch64 aarch64 GNU/Linux）上执行启动容器命令报错。报错如下：exec /bin/sh: exec format error。我需要怎么做？

**Comment by futuretech6** [comment]
我没arm的机器，理论上aarch64会自动拉arm64的镜像，应该不存在启动问题才对

**Comment by LeoBoy1st** [comment]
刚一直在百度搜索，
我看到dockerfile开头有指定。FROM --platform=$BUILDPLATFORM alpine AS build
所以很奇怪，不知道问题出在哪儿。
我现在尝试直接明确指定生成镜像试一下。
